### ISSUE TITLE
Is Vaadin 21 supported?

### ISSUE THREAD

**Issue by hfazai** [vaadin-component-factory/enhanced-dialog#16]
Enhanced dialog works fine with Vaadin 18.0.3. But with Vaadin 21, resizing and dragging is not working.

It shows these errors:
- when resize the dialog:
![image](https://user-images.githubusercontent.com/57005249/133093391-ff122658-5a04-44c5-a5f5-90add75fec05.png)

- when drag the dialog
![image](https://user-images.githubusercontent.com/57005249/133093283-529b52fe-f394-4f45-9256-62f22ef08444.png)

**Comment by jcgueriaud1** [comment]
A new version has been released on the directory: 21.0.0 which is compatible with Vaadin 21

**Comment by hfazai** [comment]
@jcgueriaud1 Thanks!
